config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'courses#index'
  get '/welcome', to: 'welcome#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    resources :courses, only: %i(new edit create update destroy) 
  end
  resources :courses, only: %i(index show)
  resources :categories do
    member do
      get 'add_courses'
      patch 'update_courses'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login, only: :index

  def index
    return if current_user.nil?

    @taught_count = @current_user.taught_courses.count
  end
end

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <% if logged_in? %>
      <h1 class="display-4"><%= link_to current_user.full_name, user_path(current_user) %></h1>
      <p class="lead">
        <%= t('views.welcome.taught_count', 
              count: @taught_count,
              course: humanize(Course, @taught_count).downcase) %>
      </p>
      <hr class="my-4">
      <p class="lead">
        <%= link_to t('views.welcome.explore_courses'),
                    courses_path,
                    class: "btn btn-primary btn-lg" %>
        <%= link_to t('button.create', resource: humanize(Course)), 
                    new_user_course_path(current_user.id),
                    class: "btn btn-primary btn-lg" %>
      </p>
    <% else %>
      <h1 class="display-4"><%= t('views.welcome.title') %></h1>
      <p class="lead"><%= t('views.welcome.aim') %></p>
      <hr class="my-4">
      <p><%= t('views.welcome.join_us') %></p>
      <p class="lead">
        <%= link_to t('button.signup'), signup_path, class: "btn btn-primary btn-lg" %>
        <%= link_to t('button.login'), login_path, class: "btn btn-secondary btn-lg" %>
      </p>
    <% end %>
  </div>
</div>