config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'courses#index'
  get '/welcome', to: 'welcome#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    resources :courses, only: %i(new edit create update destroy) 
  end
  resources :courses, only: %i(index show)
  resources :categories do
    member do
      get 'add_courses'
      patch 'update_courses'
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses, dependent: :nullify

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, except: %i(index new create)
  before_action :require_admin, except: %i(index show)
  before_action :check_update_courses_params, only: :update_courses
  skip_before_action :require_login, only: %i(index show)

  def index
    @categories = Category.order(name: :asc)
  end

  def show
    @courses =  @category.courses.page(params[:page])
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.js { flash.now[:success] = I18n.t('notice.create.success', resource: humanize(Category)) }
      else
        format.js { flash.now[:danger] = I18n.t('notice.create.failure', resource: humanize(Category)) }
      end
    end
  end

  def update
    if @category.update(category_params)
      flash[:success] = 'Category updated successfully!'
      redirect_to categories_path
    else
      error_reason = @category.errors.full_messages.join('. ')
      flash.now[:danger] = "Failed to update category details! Reason: #{error_reason}."
      render :edit, status: :bad_request
    end
  end

  def destroy
    respond_to do |format|
      if @category.destroy
        format.js { flash.now[:success] = I18n.t('notice.delete.success', resource: humanize(Category)) }
      else
        format.js { flash.now[:danger] = I18n.t('notice.delete.failure', resource: humanize(Category)) }
      end
    end
  end

  def add_courses
    @courses = Course.where(category_id: nil)
  end

  def update_courses
    update_courses_msg(update_courses_action, params[:course_ids].size)
    redirect_to @category
  rescue ActiveRecord::InvalidForeignKey
    flash[:danger] = 'Failed to update courses with category! Reason: Invalid Category Id.'
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Category not found!'
    redirect_to categories_path
  end

  def check_update_courses_params
    return if params[:course_ids]

    flash[:danger] = 'No course was selected to update.'
    redirect_to categories_path
  end

  def update_courses_msg(update_count, params_size)
    if params_size > update_count
      flash[:danger] = "#{update_count}/#{params_size} course successfully updated."
    else
      flash[:success] = 'Courses successfully updated with category!'
    end
  end

  def update_courses_action
    Course.where(id: params[:course_ids]).update_all(category_id: @category.id)
  end

  def category_params
    params[:category].permit(:name)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_user, except: %i(index show search)
  before_action :find_course, only: %i(edit update destroy show)
  skip_before_action :require_login, only: :index

  def index
    if params[:search].present?
      @query = params[:search][:query]
      @page = params[:search][:page].to_i.abs
      @courses = Course.find_course(@query).paginate(@page)
      render :search
    else
      all_courses = if params[:category_id]
                      Course.where(category_id: params[:category_id])
                    else
                      Course.all
                    end
      @courses = all_courses.page(params[:page])
      respond_to { |format| format.js } if request.xhr?
      @categories = Category.all
    end
  end

  def show; end

  def new
    @course = Course.new
  end

  def edit; end

  def create
    @course = @user.taught_courses.new(course_params)

    if @course.save
      flash[:success] = I18n.t('notice.create.success', resource: humanize(Course))
      redirect_to courses_path
    else
      flash[:danger] = I18n.t('notice.create.failure', resource: humanize(Course))
      render :new, status: :bad_request
    end
  end

  def update
    if @course.update(course_params)
      flash[:success] = I18n.t('notice.update.success', resource: humanize(Course))
      redirect_to @course
    else
      flash[:danger] = I18n.t('notice.update.failure', resource: humanize(Course))
      render :edit, status: :bad_request
    end
  end

  def destroy
    if @course.destroy
      flash[:success] = I18n.t('notice.delete.success', resource: humanize(Course))
    else
      flash[:danger] = I18n.t('notice.delete.failure', resource: humanize(Course))
    end
    redirect_to courses_path
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = I18n.t('notice.record_not_found',
                            resource: humanize(User),
                            id: params[:user_id])
    redirect_to courses_path
  end

  def find_course
    @course = if @user.nil? || current_user.admin
                Course.find(params[:id])
              else
                @user.taught_courses.find(params[:id])
              end
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = I18n.t('notice.record_not_found',
                            resource: humanize(Course),
                            id: params[:id])
    redirect_to courses_path
  end

  def course_params
    params.require(:course).permit(:title, :category_id, :video_tutorial, :thumbnails)
  end
end

app/views/categories/_category.html.erb
<tr>
  <td><%= link_to category.name.titleize, category_path(category) %></td>
  <td><%= date_parses(category.created_at) %></td>
  <td><%= category.courses.count %></td>
  <div id="delete">
    <td class="table__action">
      <%= link_to 'View',
                  category_path(category),
                  class: "btn btn-success btn-sm" %>
      <% if logged_in? && current_user.admin %>
        <%= link_to 'Edit', 
                    edit_category_path(category),
                    class: "btn btn-primary btn-sm" %>
        <%= link_to 'Delete',
                    category_path(category),
                    method: :delete,
                    data: { confirm: 'Are you sure?' },
                    class: "btn btn-danger btn-sm delete",
                    remote: true %>
      <% end %>
    </td>
  </div>
</tr>

app/views/categories/_form.html.erb
<%= simple_form_for category, remote: true do |f| %>
  <div class="form-style">
    <%= render "shared/errors", obj: category %>
    <%= f.error_notification %>
    <%= f.input :name, label: 'Name', required: true %>
    <%= f.button :submit, class: "btn-primary" %>
    <%= f.button :button, 'Reset', type: 'reset', class: "btn-outline-secondary" %>
  </div>
<% end %>

app/views/categories/add_courses.html.erb
<div class="container align-items-center">
  <div class="table-responsive">
    <div class="table-wrapper">
      <h1 class="text-center title">
        Add Courses to <%= @category.name %> Category
      </h1>
    </div>
    <br>
    <%= simple_form_for @category, url: update_courses_category_path(@category), method: :patch do |form| %>
      <table class="table form-style">
        <thead>
          <tr>
            <th>Select</th>
            <th>Course Title</th>
          </tr>
        </thead>
        <% @courses.each do |course| %>
          <tbody>
            <tr>
              <td><%= check_box_tag "course_ids[]", course.id %></td>
              <td><%= link_to course.title, course_path(course) %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <%= form.submit 'Update Courses', class: 'btn btn-success btn-lg' %>
    <% end %>
  </div>
</div>

app/views/categories/create.js.erb
$('#new-category form').remove();
$('#ajax-flash').append("<%= j render partial: 'layouts/messages' %>");
<% if @category.id.present?  %>
  $('#new-category a').show();
  $('table#categories tbody').append("<%= j render @category %>")
<% else %>
  $('#new-category a').hide().parent().append("<%= j render 'form', category: @category %>")
<% end %>

app/views/categories/destroy.js.erb
$('#ajax-flash').append("<%= j render partial: 'layouts/messages' %>");
<% if @category.errors.blank? %>
  $('.delete').bind('ajax:success',function(){
    $(this).closest('tr').fadeOut();
  });
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center title">Edit Category</h1>
      <br>
      <%= render 'form', category: @category %>
      <%= link_to 'Add Courses',
                  add_courses_category_path(@category),
                  class: "button btn btn-primary btn-bottom" %>
      <%= link_to 'Delete Category',
                  category_path(@category),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: "button btn btn-danger btn-bottom" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container align-items-center">
  <div class="table-responsive">
    <div class="table-wrapper">
      <div class="table-title">
        <h2 class="table-title__text">All Categories</h2>
      </div>
    </div>
    <table class="table table-striped table-hover" id="categories">
      <thead>
        <tr>
          <th>Name</th>
          <th>Created On</th>
          <th>Total Videos</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: :category, collection: @categories %>
      </tbody>
    </table>
    <% if logged_in? && current_user.admin %>
      <div id="new-category">
        <%= link_to t('button.new', resource: humanize(Category)),
                    new_category_path,
                    class: "btn btn-lg btn-outline-success btn-bottom",
                    remote: true %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.js.erb
$('#new-category a').hide().parent().append("<%= j render 'form', category: @category %>")

app/views/categories/show.html.erb
<div class="container">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="card parent">
        <div class="card-header bg-primary">
          <h1>Available Videos In <%= @category.name %> Category</h1>
        </div>
        <%= render 'users/courses', courses: @courses %>
      </div>
    </div>
  </div>
</div>