config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'courses#index'
  get '/welcome', to: 'welcome#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    resources :courses, only: %i(new edit create update destroy) 
  end
  resources :courses, only: %i(index show)
  resources :categories do
    member do
      get 'add_courses'
      patch 'update_courses'
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark footer">
  <div class="container text-center">
    <small>Copyright &copy; <%='Shuvra Debnath' %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div id= 'flash-container' class="container">
  <% flash.each do |msg_type, msg| %>
    <div class="alert alert-<%= msg_type %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark default-color">
  <%= link_to t('views.layouts.eLearning'), root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false" 
          aria-label="Toggle navigation" >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to t(humanize(Category, 2)), categories_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to t('views.layouts.people'), users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
             role="button"
             data-toggle="dropdown"
             aria-haspopup="true"
             aria-expanded="false"> <%= t('views.shared.profile') %> </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to t('button.view', resource: t('views.shared.profile')),
                        user_path(current_user),
                        class: "dropdown-item" %>
            <%= link_to t('button.edit', resource: t('views.shared.profile')),
                        edit_user_path(current_user),
                        class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to t('views.layouts.my_courses'),
                        user_path(current_user),
                        class: "dropdown-item" %>
          </div>
        </li>
        <% if current_user.admin %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"
               role="button"
               data-toggle="dropdown"
               aria-haspopup="true"
               aria-expanded="false"><%= t('views.layouts.manage', resource: '') %></a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to t('views.layouts.manage', resource: humanize(User, 2)),
                          users_path,
                          class: "dropdown-item" %>
              <%= link_to t('views.layouts.manage', resource: humanize(Category, 2)),
                          categories_path,
                          class: "dropdown-item" %>
              <%= link_to t('views.layouts.manage', resource: humanize(Course, 2)),
                          courses_path,
                          class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to t('button.logout'), logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t('button.login'), login_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <%= render partial: 'layouts/search' %>
  </div>
</nav>

app/views/layouts/_search.html.erb
<%= simple_form_for :search,
                    url: courses_path,
                    method: 'GET',
                    html: { class: "form-inline my-2 my-lg-0",
                            onsubmit: 'return validate(event)' } do |f| %>
  <%= f.input :query,
              label: false,
              placeholder: t('views.layouts.search_placeholder'),
              input_html: { id: 'search-text', value: '' },
              class: "form-control mr-sm-2" %>
  <%= f.submit t('views.layouts.search'),
                data: { disable_with: false },
                class: "btn btn-outline-success my-2 my-sm-0 bg-light" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ELearning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column">
      <%= render 'layouts/navigation' %>
      <div id="page-content">
        <div id="ajax-flash"></div>
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
  </body>
</html>